import * as THREE from 'three';

/**
 * MapLayout — balanced 6v6 map design for GUNZ.
 *
 * Responsibilities:
 *  - Spawn zone markers: colored ground pads at each team's deployment zone.
 *  - River lanes: two east-west mud channels crossing the battlefield at
 *    z ≈ ±26.  Tanks and soldiers are slowed in these zones.
 *  - `isInRiver(x, z)`: query used by movement systems to apply the
 *    40 % (tank) / 60 % (soldier) speed penalty defined in VISION.md.
 *
 * Note: Village buildings are generated by VillageGenerator (t047/t048).
 * MapLayout does not own or manage building geometry.
 *
 * Layout overview (Z axis = north-south, X axis = east-west):
 *
 *   z = -70  ┌──────────────────────────────────┐  Team 1 (enemy) spawn zone
 *            │                                  │
 *   z = -26  │ ══════════ north river ══════════ │  movement penalty band
 *            │                                  │
 *   z =   0  │         [ village ]              │  center village (VillageGenerator)
 *            │                                  │
 *   z = +26  │ ══════════ south river ══════════ │  movement penalty band
 *            │                                  │
 *   z = +70  └──────────────────────────────────┘  Team 0 (player) spawn zone
 *
 * All geometry is added directly to the THREE.Scene (not as terrain children)
 * so world positions equal mesh positions, consistent with TreeSystem and
 * WreckSystem conventions.
 *
 * This module is persistent — `reset()` is a no-op because map geometry does
 * not change between rounds.
 */

// ─── Spawn zone configuration ────────────────────────────────────────────────

/**
 * Spawn zone definitions.  Each entry describes a coloured ground pad that
 * visually marks where a team's tanks deploy at the start of each round.
 * The actual spawn positions are calculated by TeamManager._spawnPosition().
 *
 * width / depth are in world units (X and Z spans respectively).
 * Alpha-blended so the terrain colour shows through.
 */
const SPAWN_ZONE_DEFS = [
  // Team 0 — player side (green, south)
  { teamId: 0, centerX: 0, centerZ: 57, width: 38, depth: 16, color: 0x3a7a33 },
  // Team 1 — enemy side (red, north)
  { teamId: 1, centerX: 0, centerZ: -57, width: 38, depth: 16, color: 0xb03000 },
];

// ─── River lane configuration ─────────────────────────────────────────────────

/**
 * River / mud zone definitions.  Each zone is a wide east-west band.
 *
 * centerZ — world Z position of the river centre line.
 * depth   — north-south width of the mud zone in world units.
 * width   — east-west extent (spans the full traversable map width).
 * color   — rendered as a semi-transparent muddy-water plane.
 *
 * Movement penalties applied when `isInRiver()` returns true:
 *   Tanks: 40 % speed (i.e. multiply by RIVER_SPEED_TANK)
 *   Soldiers: 60 % speed (i.e. multiply by RIVER_SPEED_SOLDIER)
 */
const RIVER_DEFS = [
  { centerZ: -26, depth: 10, width: 160, color: 0x2a5f8a },  // north river
  { centerZ: +26, depth: 10, width: 160, color: 0x2a5f8a },  // south river
];

// Movement-speed multipliers while inside a river zone.
export const RIVER_SPEED_TANK    = 0.40;
export const RIVER_SPEED_SOLDIER = 0.60;

// ─── MapLayout class ──────────────────────────────────────────────────────────

export class MapLayout {
  /**
   * @param {THREE.Scene}                              scene
   * @param {import('../entities/Terrain.js').Terrain} terrain
   */
  constructor(scene, terrain) {
    this._scene   = scene;
    this._terrain = terrain;

    /**
     * River zone descriptors for fast containment tests.
     * @type {Array<{minZ: number, maxZ: number}>}
     */
    this._riverZones = [];

    this._buildSpawnZones();
    this._buildRivers();
  }

  // ─── Public API ─────────────────────────────────────────────────────────────

  /**
   * Returns true when the point (x, z) lies inside any river / mud zone.
   * Used by movement systems to apply speed penalties.
   *
   * @param {number} _x  — world X (unused; rivers span the full map width)
   * @param {number} z   — world Z
   * @returns {boolean}
   */
  isInRiver(_x, z) {
    for (const zone of this._riverZones) {
      if (z >= zone.minZ && z <= zone.maxZ) return true;
    }
    return false;
  }

  /**
   * No-op — map geometry persists across round resets.
   */
  reset() {
    return 0;
  }

  // ─── Private builders ────────────────────────────────────────────────────────

  /** Create semi-transparent coloured ground pads for each spawn zone. */
  _buildSpawnZones() {
    for (const def of SPAWN_ZONE_DEFS) {
      const geo = new THREE.PlaneGeometry(def.width, def.depth);
      geo.rotateX(-Math.PI / 2);

      const mat = new THREE.MeshStandardMaterial({
        color:       def.color,
        roughness:   1.0,
        metalness:   0.0,
        transparent: true,
        opacity:     0.45,
        flatShading: true,
        depthWrite:  false,
      });

      const mesh = new THREE.Mesh(geo, mat);
      const y = this._terrain.getHeightAt(def.centerX, def.centerZ) + 0.05;
      mesh.position.set(def.centerX, y, def.centerZ);
      mesh.receiveShadow = false;
      this._scene.add(mesh);
    }
  }

  /** Create translucent muddy-water planes for the two river zones. */
  _buildRivers() {
    for (const def of RIVER_DEFS) {
      // Visual plane — sits a couple centimetres above terrain to avoid z-fighting
      const geo = new THREE.PlaneGeometry(def.width, def.depth);
      geo.rotateX(-Math.PI / 2);

      const mat = new THREE.MeshStandardMaterial({
        color:       def.color,
        roughness:   0.6,
        metalness:   0.1,
        transparent: true,
        opacity:     0.70,
        flatShading: true,
        depthWrite:  false,
      });

      const mesh = new THREE.Mesh(geo, mat);
      // Sample terrain height at river centre and raise slightly
      const y = this._terrain.getHeightAt(0, def.centerZ) + 0.08;
      mesh.position.set(0, y, def.centerZ);
      mesh.receiveShadow = false;
      this._scene.add(mesh);

      // Register the containment band for isInRiver() queries
      this._riverZones.push({
        minZ: def.centerZ - def.depth / 2,
        maxZ: def.centerZ + def.depth / 2,
      });
    }
  }
}
